# Generated by Django 3.2.9 on 2021-12-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='conatent',
            new_name='content',
        ),
    ]
